permalink   : /posts/:title/
#markdown    : kramdown
#highlighter : pygments
timezone: Europe/Moscow
language: ru

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

name: Web Dev Blog by Artur Sh. Mamedbekov
title: Bashka
description: "Web Dev Blog by Artur Sh. Mamedbekov"
keywords: "Blog, Web, Develop, PHP, JS, Doctrine, Zend Framework, RequireJS, BackboneJS, Git, Gulp, Bash"
url: http://bashka.github.io
baseurl: ""
domain_name: bashka.github.io
# google_analytics: UA-52446115-1
yandex_metrika: 40061125
repo: http://github.com/Bashka/bashka.github.io
disqus_shortname: "bashka-github-io"
onesignal:
  id: "44b964b3-c148-48f7-a1fa-166e958bceb1"
  safari_id: "web.onesignal.auto.2ccd5ae7-3528-4a1e-96f6-138881299499"
  subdomain: "bashka-github"

author_themes:
  name      : Fernando Moreira
  image     : /assets/images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."
author_blog:
  name      : Artur Sh. Mamedbekov
  email     : Artur-Mamedbekov@yandex.ru
  github    : http://github.com/bashka

gems: ["jekyll-paginate"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
