permalink   : /:categories/:year/:title/
#markdown    : kramdown
#highlighter : pygments
timezone: Europe/Moscow

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: WebDev blog by Artur Sh. Mamedbekov
title: WebDevBlog
description: "WebDev blog by Artur Sh. Mamedbekov"
keywords: "Web, PHP, JS, Doctrine, Zend Framework"
#url: http://nandomoreira.me
baseurl: ""
#domain_name: nandomoreira.me
# google_analytics: UA-52446115-1
#repo: http://github.com/nandomoreirame/mug
#disqus_shortname: "nandothemes"

author_themes:
  name      : Fernando Moreira
  image     : /assets/images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."
author_blog:
  name      : Artur Sh. Mamedbekov
  email     : Artur-Mamedbekov@yandex.ru
  github    : http://github.com/bashka

gems: ["jekyll-paginate"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
